[package]
name = "tokengrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tokengrams"
crate-type = ["cdylib", "rlib"]

[dependencies]
ahash = "0.8.7"
anyhow = "1.0.79"
bincode = "1.3.3"
flate2 = "1.0.28"
indicatif = "0.17.7"
itertools = "0.12.0"
pyo3 = { version = "0.20.1", features = ["anyhow", "extension-module"] }
serde = { version = "1.0.195", features = ["derive"] }
sucds = "0.8.1"
utf16_literal = "0.2.1"
yada = "0.5.0"

[[test]]
name = "tests"
path = "tests/tests.rs"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
rand = "0.8.4"
