[package]
name = "tokengrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tokengrams"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.7"
anyhow = "1.0.79"
bincode = "1.3.3"
flate2 = "1.0"
indicatif = "0.17.7"
pyo3 = { version = "0.20.1", features = ["anyhow", "extension-module"] }
serde = { version = "1.0.195", features = ["derive"] }
sucds = "0.8.1"
tokenizers = { version = "0.15.0", features = ["http"] }
yada = "0.5.0"

[dev-dependencies]
rand = "0.8.4"
