[package]
name = "tokengrams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
rayon = "1.8.0"
serde_json = "1.0.108"
tokenizers = { version = "0.15.0", features = ["http"] }
tongrams = { git = "https://github.com/norabelrose/tongrams-rs.git" }
zstd = "0.13.0"
