from pathlib import Path


class Trie:
    """A trie of token n-grams."""
    @staticmethod
    def from_files(filepaths: list[str | Path], fmt: str) -> 'Trie': ...
    @staticmethod
    def from_bytes(bytes: list[int]) -> 'Trie': ...
    @staticmethod
    def from_texts(texts: list[str]) -> 'Trie': ...
    def find(self, gram: str) -> int | None: ...
    def num_orders(self) -> int: ...
    def num_grams(self) -> int: ...
    def to_bytes(self) -> list[int]: ...