from pathlib import Path


class TokenTrie:
    """A trie of token n-grams."""
    def find(self, gram: list[int]) -> int | None: ...
    def num_orders(self) -> int: ...
    def num_grams(self) -> int: ...
    def to_bytes(self) -> bytes: ...


class WordTrie:
    """A trie of word n-grams."""
    @staticmethod
    def from_files(filepaths: list[str | Path], fmt: str) -> 'WordTrie': ...
    @staticmethod
    def from_bytes(bytes: list[int]) -> 'WordTrie': ...
    @staticmethod
    def from_texts(texts: list[str]) -> 'WordTrie': ...
    def find(self, gram: str) -> int | None: ...
    def num_orders(self) -> int: ...
    def num_grams(self) -> int: ...
    def to_bytes(self) -> bytes: ...