name: Manual Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maturin
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
